Accessing Data with Pandas

In [1]:
import pandas as pd

In [2]:
# lets read all data files

coffe = pd.read_csv("./Warmup Data/coffee.csv")
result = pd.read_parquet("./Data/results.parquet")
ympics_data=pd.read_excel("./Data/olympics-data.xlsx", sheet_name="results")
bios=pd.read_csv("./Data/bios.csv")

In [3]:
print(coffe)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [4]:
display(coffe)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [5]:
coffe.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [6]:
coffe.tail(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [7]:
coffe.sample(10)  # To get random datas

          Day Coffee Type  Units Sold
7    Thursday       Latte          30
11   Saturday       Latte          35
0      Monday    Espresso          25
13     Sunday       Latte          35
10   Saturday    Espresso          45
6    Thursday    Espresso          40
8      Friday    Espresso          45
4   Wednesday    Espresso          35
12     Sunday    Espresso          45
3     Tuesday       Latte          20

To Access specific value we use loc and iloc

In [8]:
# Loc
# coffe.loc[Rows, Coloumn]

coffe.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [9]:
coffe.loc[[0,1,5]]  # To print 1st,2nd and 6th rows

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [10]:
coffe.loc[1:3]

       Day Coffee Type  Units Sold
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [11]:
coffe.loc[1:5, ["Day","Units Sold"]]

         Day  Units Sold
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25

iloc