Accessing Data with Pandas

In [1]:
import pandas as pd

In [2]:
# lets read all data files

coffe = pd.read_csv("./Warmup Data/coffee.csv")
result = pd.read_parquet("./Data/results.parquet")
ympics_data=pd.read_excel("./Data/olympics-data.xlsx", sheet_name="results")
bios=pd.read_csv("./Data/bios.csv")

In [3]:
print(coffe)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [4]:
display(coffe)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [5]:
coffe.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [6]:
coffe.tail(10)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [7]:
coffe.sample(10)  # To get random datas

          Day Coffee Type  Units Sold
7    Thursday       Latte          30
11   Saturday       Latte          35
0      Monday    Espresso          25
13     Sunday       Latte          35
10   Saturday    Espresso          45
6    Thursday    Espresso          40
8      Friday    Espresso          45
4   Wednesday    Espresso          35
12     Sunday    Espresso          45
3     Tuesday       Latte          20

To Access specific value we use loc and iloc

In [8]:
# Loc
# coffe.loc[Rows, Coloumn]

coffe.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [9]:
coffe.loc[[0,1,5]]  # To print 1st,2nd and 6th rows

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
5  Wednesday       Latte          25

In [16]:
coffe.loc[1:3]

       Day Coffee Type  Units Sold
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [ ]:
coffe.loc[1:5, ["Day","Units Sold"]]

         Day  Units Sold
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25

iloc

In [30]:
# iloc is similar to loc instead of giving lables here we use only integers ## ie Only uses
# Index values
coffe.iloc[:, [0,2]]

                 Day  Units Sold
Day
Monday        Monday          25
Monday        Monday          15
Tuesday      Tuesday          30
Tuesday      Tuesday          20
Wednesday  Wednesday          35
Wednesday  Wednesday          25
Thursday    Thursday          40
Thursday    Thursday          30
Friday        Friday          45
Friday        Friday          35
Saturday    Saturday          45
Saturday    Saturday          35
Sunday        Sunday          45
Sunday        Sunday          35

Other Stuff

In [21]:
coffe.index=coffe.Day

coffe.iloc[0:5, [0,1]]

                 Day Coffee Type
Day
Monday        Monday    Espresso
Monday        Monday       Latte
Tuesday      Tuesday    Espresso
Tuesday      Tuesday       Latte
Wednesday  Wednesday    Espresso

In [23]:
coffe.head() # Now the index has been changed to day wise

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [25]:
coffe.loc["Monday"]

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [27]:
coffe.loc["Monday": "Tuesday"]

             Day Coffee Type  Units Sold
Day
Monday    Monday    Espresso          25
Monday    Monday       Latte          15
Tuesday  Tuesday    Espresso          30
Tuesday  Tuesday       Latte          20

In [29]:
coffe.loc["Monday": "Tuesday", "Units Sold"]

Day
Monday     25
Monday     15
Tuesday    30
Tuesday    20
Name: Units Sold, dtype: int64

In [31]:
coffe = pd.read_csv("./Warmup Data/coffee.csv")

Setting Values

In [37]:
coffe.loc[1:3, "Units Sold"] = 10
coffe.loc[1:3]

       Day Coffee Type  Units Sold
1   Monday       Latte          10
2  Tuesday    Espresso          10
3  Tuesday       Latte          10

Optimized way to get single values (.at & .iat)

In [43]:
coffe.at[0, "Units Sold"]

np.int64(25)

In [42]:
coffe.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          10
3    Tuesday       Latte          10
4  Wednesday    Espresso          35

In [44]:
coffe.iat[3,1]

'Latte'

In [51]:
coffe.iat[3,0]

'Tuesday'

Getting Columns

In [53]:
coffe.Day

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [54]:
coffe.head(4)

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          10
2  Tuesday    Espresso          10
3  Tuesday       Latte          10

In [61]:
coffe["Coffee Type"]

0     Espresso
1        Latte
2     Espresso
3        Latte
4     Espresso
5        Latte
6     Espresso
7        Latte
8     Espresso
9        Latte
10    Espresso
11       Latte
12    Espresso
13       Latte
Name: Coffee Type, dtype: object

In [62]:
coffe["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

Sort Values

In [63]:
coffe.sort_values(["Units Sold"], ascending=True)

          Day Coffee Type  Units Sold
1      Monday       Latte          10
2     Tuesday    Espresso          10
3     Tuesday       Latte          10
0      Monday    Espresso          25
5   Wednesday       Latte          25
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [75]:
coffe.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          10
1      Monday       Latte          10
3     Tuesday       Latte          10


Iterate over dataframe with for loop

In [79]:
for index, row in coffe.iterrows():
    print(index)
    print(row)

    print("Coffe Type of Row:", row["Coffee Type"])

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object
Coffe Type of Row: Espresso
1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object
Coffe Type of Row: Latte
2
Day             Tuesday
Coffee Type    Espresso
Units Sold           10
Name: 2, dtype: object
Coffe Type of Row: Espresso
3
Day            Tuesday
Coffee Type      Latte
Units Sold          10
Name: 3, dtype: object
Coffe Type of Row: Latte
4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object
Coffe Type of Row: Espresso
5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object
Coffe Type of Row: Latte
6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object
Coffe Type of Row: Espresso
7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object
Coffe Type of Row: Latte
8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object
Coffe Type of Row: Espresso
9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object
Coffe Type of Row: Latte
10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object
Coffe Type of Row: Espresso
11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object
Coffe Type of Row: Latte
12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object
Coffe Type of Row: Espresso
13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object
Coffe Type of Row: Latte

Filtering Data

In [80]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [83]:
bios.loc[bios["height_cm"]>215]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5796,5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
6223,6250,Lars Hansen,1954-09-27,København (Copenhagen),Hovedstaden,DEN,Canada,216.0,105.0,NaN
6270,6298,Hu Zhangbao,1963-04-05,NaN,NaN,NaN,People's Republic of China,216.0,135.0,NaN
6409,6440,Sergey Kovalenko,1947-08-11,NaN,NaN,NaN,Soviet Union,216.0,111.0,2004-11-18
6420,6451,Jānis Krūmiņš,1930-01-30,Cēsis,Cēsu novads,LAT,Soviet Union,218.0,141.0,1994-11-20
6504,6537,Luc Longley,1969-01-19,Melbourne,Victoria,AUS,Australia,220.0,135.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
7074,7111,Paulo da Silva,1963-07-21,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
7188,7226,Vladimir Tkachenko,1957-09-20,Golovinka,Krasnodar Kray,RUS,Soviet Union,220.0,110.0,NaN
7281,7320,Stojko Vranković,1964-01-22,Drniš,Šibensko-kninska županija,CRO,Croatia Yugoslavia,217.0,115.0,NaN
7376,7416,Eurelijus Žukauskas,1973-08-22,Klaipėda,Klaipėda,LTU,Lithuania,218.0,115.0,NaN
52608,52983,Aleksey Kazakov,1976-03-18,Naberezhnye Chelny,Respublika Tatarstan,RUS,Russian Federation,217.0,102.0,NaN
82100,82753,Frédéric Weis,1977-06-22,Thionville,Moselle,FRA,France,218.0,110.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
107408,108533,Peter John Ramos,1985-05-23,Fajardo,Puerto Rico,PUR,Puerto Rico,219.0,113.0,NaN
112312,113568,Stanko Barać,1986-08-13,Mostar,Hercegovačko-neretvanski kanton,BIH,Croatia,217.0,110.0,NaN
112332,113588,Andreas Glyniadakis,1981-08-26,Chania,Kriti,GRE,Greece,216.0,115.0,NaN
112337,113593,Hamed Haddadi,1985-05-19,Ahvaz,Khuzestan,IRI,Islamic Republic of Iran,218.0,110.0,NaN
118663,120400,Timofey Mozgov,1986-07-16,NaN,NaN,NaN,Russian Federation,216.0,113.0,NaN
118676,120415,Dmitry Musersky,1988-10-29,Makiïvka,Donetsk,UKR,Russian Federation,219.0,104.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN
121694,123709,Salah Mejri,1986-06-15,Jendouba,Jendouba,TUN,Tunisia,216.0,110.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
130460,133147,Li Muhao,1992-06-02,Guiyang,Guizhou,CHN,People's Republic of China,218.0,115.0,NaN
130461,133148,Zhou Qi,1996-01-16,Xinxiang,Henan,CHN,People's Republic of China,217.0,95.0,NaN
138671,142084,Ondřej Balvín,1992-09-20,Ústí nad Labem,Ústecký kraj,CZE,Czechia,216.0,107.0,NaN
139365,142836,Moustapha Fall,1992-02-23,Paris,Paris,FRA,France,218.0,NaN,NaN

In [86]:
bios.loc[bios["height_cm"] > 215, ["athlete_id","name", "height_cm"]]

        athlete_id                   name  height_cm
5089          5108     Viktor Pankrashkin      220.0
5583          5606   Paulinho Villas Boas      217.0
5673          5696         Gunther Behnke      221.0
5716          5739               Uwe Blab      218.0
5781          5804         Tommy Burleson      223.0
5796          5819          Andy Campbell      218.0
6223          6250            Lars Hansen      216.0
6270          6298            Hu Zhangbao      216.0
6409          6440       Sergey Kovalenko      216.0
6420          6451          Jānis Krūmiņš      218.0
6504          6537            Luc Longley      220.0
6722          6755       Shaquille O'Neal      216.0
6937          6972         David Robinson      216.0
6978          7013        Arvydas Sabonis      223.0
7074          7111         Paulo da Silva      217.0
7188          7226     Vladimir Tkachenko      220.0
7281          7320       Stojko Vranković      217.0
7376          7416    Eurelijus Žukauskas      218.0
52608        52983        Aleksey Kazakov      217.0
82100        82753          Frédéric Weis      218.0
89070        89782               Yao Ming      226.0
89075        89787         Roberto Dueñas      221.0
107408      108533       Peter John Ramos      219.0
112312      113568           Stanko Barać      217.0
112332      113588    Andreas Glyniadakis      216.0
112337      113593          Hamed Haddadi      218.0
118663      120400         Timofey Mozgov      216.0
118676      120415        Dmitry Musersky      219.0
120266      122147           Zhang Zhaoxu      221.0
121694      123709            Salah Mejri      216.0
123850      126093         Tyson Chandler      216.0
130460      133147               Li Muhao      218.0
130461      133148                Zhou Qi      217.0
138671      142084          Ondřej Balvín      216.0
139365      142836         Moustapha Fall      218.0

Short-hand syntax (without .loc)

In [88]:
bios[bios['height_cm']>220][["name", "height_cm"]]

                   name  height_cm
5673     Gunther Behnke      221.0
5781     Tommy Burleson      223.0
6978    Arvydas Sabonis      223.0
89070          Yao Ming      226.0
89075    Roberto Dueñas      221.0
120266     Zhang Zhaoxu      221.0

Multiple filter conditions

In [89]:
bios[(bios["height_cm"]>220) & (bios["born_country"] =="USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN

Filter by string conditions

In [90]:
bios[bios["name"].str.contains("keith", case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [ ]:
#  Regex syntax  here we are using an or |

bios[bios['name'].str.contains('keith|patrick', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [92]:
# Other cool regex filters

# Find athletes born in cities that start with a vowel:
vowel_cities = bios[bios['born_city'].str.contains(r'^[AEIOUaeiou]', na=False)]

# Find athletes with names that contain exactly two vowels:
two_vowels = bios[bios['name'].str.contains(r'^[^AEIOUaeiou]*[AEIOUaeiou][^AEIOUaeiou]*[AEIOUaeiou][^AEIOUaeiou]*$', na=False)]

# Find athletes with names that have repeated consecutive letters (e.g., "Aaron", "Emmett"):
repeated_letters = bios[bios['name'].str.contains(r'(.)\1', na=False)]

# Find athletes with names ending in 'son' or 'sen':
son_sen_names = bios[bios['name'].str.contains(r'son$|sen$', case=False, na=False)]

# Find athletes born in a year starting with '19':
born_19xx = bios[bios['born_date'].str.contains(r'^19', na=False)]

# Find athletes with names that do not contain any vowels:
no_vowels = bios[bios['name'].str.contains(r'^[^AEIOUaeiou]*$', na=False)]

# Find athletes whose names contain a hyphen or an apostrophe:
hyphen_apostrophe = bios[bios['name'].str.contains(r"[-']", na=False)]

# Find athletes with names that start and end with the same letter:
start_end_same = bios[bios['name'].str.contains(r'^(.).*\1$', na=False, case=False)]

# Find athletes with a born_city that has exactly 7 characters:
city_seven_chars = bios[bios['born_city'].str.contains(r'^.{7}$', na=False)]

# Find athletes with names containing three or more vowels:
three_or_more_vowels = bios[bios['name'].str.contains(r'([AEIOUaeiou].*){3,}', na=False)]

C:\Users\abbas\AppData\Local\Temp\ipykernel_17260\1632287501.py:10: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  repeated_letters = bios[bios['name'].str.contains(r'(.)\1', na=False)]
C:\Users\abbas\AppData\Local\Temp\ipykernel_17260\1632287501.py:25: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  start_end_same = bios[bios['name'].str.contains(r'^(.).*\1$', na=False, case=False)]
C:\Users\abbas\AppData\Local\Temp\ipykernel_17260\1632287501.py:31: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  three_or_more_vowels = bios[bios['name'].str.contains(r'([AEIOUaeiou].*){3,}', na=False)]

In [93]:
# Don't use regex search (exact match)
bios[bios['name'].str.contains('keith|patrick', case=False, regex=False)]

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date]
Index: []