# Handling Null Values

Handling Null Values (NaNs) | .fillna() .interpolate() .dropna() .isna() .notna()

In [1]:
import pandas as pd
coffee = pd.read_csv("./Warmup Data/coffee.csv")
result = pd.read_parquet("./Data/results.parquet")
ympics_data=pd.read_excel("./Data/olympics-data.xlsx", sheet_name="results")
bios=pd.read_csv("./Data/bios.csv")

In [2]:
coffee.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [3]:
coffee['Units Sold']

0     25
1     15
2     30
3     20
4     35
5     25
6     40
7     30
8     45
9     35
10    45
11    35
12    45
13    35
Name: Units Sold, dtype: int64

In [5]:
import numpy as np
coffee.loc[[2,3], 'Units Sold'] = np.nan

In [6]:
# Make sure to set this to your Units Sold column if you want these changes to stick
coffee['Units Sold'].fillna(coffee['Units Sold'].mean())

0     25.000000
1     15.000000
2     34.166667
3     34.166667
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [7]:
# coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee['Units Sold'].interpolate()

0     25.000000
1     15.000000
2     21.666667
3     28.333333
4     35.000000
5     25.000000
6     40.000000
7     30.000000
8     45.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [8]:
coffee.dropna(subset=['Units Sold']) # Use inplace=True if you want to update the coffee df

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [9]:

coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [10]:

coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0